name: Repo Updater

on:
 workflow_dispatch: {}
 schedule:
   - cron: '24 19 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: corretto
        java-version: 21
    - name: Execute update.sh
      run: ./update.sh auto true
    - name: Push changes to repository (if any)
      run: git push
